eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8763
spring:
  application:
    name: lbs
  redis:
    hostName: 10.150.7.208
    port: 6379
    password: test123
    pool.maxActive: 8
    pool.maxWait: -1
    pool.maxIdle: 8
    pool.minIdle: 0
    timeout: 0
rocketmq:
  #mq的nameserver地址
  namesrvAddr: 10.150.7.208:9876
  producer:
    # 发送同一类消息的设置为同一个group，保证唯一,默认不需要设置，rocketmq会使用ip@pid(pid代表jvm名字)作为唯一标示
    groupName: lbsProducerGroup
    #如果需要同一个jvm中不同的producer往不同的mq集群发送消息，需要设置不同的instanceName
    instanceName: lbsProducer
    #topic名称
    topic: toc_lbs
    #根据实际情况设置消息的tag
    tag: test_tag
    #消息最大长度
    maxMessageSize: 131072 # 1024*128
    #发送消息超时时间
    sendMsgTimeout: 10000
  consumer:
    groupName: lbsConsumerGroup
    topic: tos_lbs
    tag: test_tag
    consumeThreadMin: 20
    consumeThreadMax: 64
    consumeBatchSize: 100

